// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GU_OfyN4Y9XHQC8F0_f5gi44j0iMS2U',
    appId: '1:897963909111:web:1c384fd6cbfe98c92418f2',
    messagingSenderId: '897963909111',
    projectId: 'kayla-test-3ccfd',
    authDomain: 'kayla-test-3ccfd.firebaseapp.com',
    storageBucket: 'kayla-test-3ccfd.appspot.com',
    measurementId: 'G-Q5L8BS3HPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtDIarzfxdjm7hnbgCPn6MKKgTR2nxq8',
    appId: '1:897963909111:android:08e15f56c2161b742418f2',
    messagingSenderId: '897963909111',
    projectId: 'kayla-test-3ccfd',
    storageBucket: 'kayla-test-3ccfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5yWZMVomT7chDqHX8O_F1R81VyPHulE',
    appId: '1:897963909111:ios:d9f4adeca34208ba2418f2',
    messagingSenderId: '897963909111',
    projectId: 'kayla-test-3ccfd',
    storageBucket: 'kayla-test-3ccfd.appspot.com',
    iosBundleId: 'com.example.keylatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5yWZMVomT7chDqHX8O_F1R81VyPHulE',
    appId: '1:897963909111:ios:d9f4adeca34208ba2418f2',
    messagingSenderId: '897963909111',
    projectId: 'kayla-test-3ccfd',
    storageBucket: 'kayla-test-3ccfd.appspot.com',
    iosBundleId: 'com.example.keylatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7GU_OfyN4Y9XHQC8F0_f5gi44j0iMS2U',
    appId: '1:897963909111:web:7c68841ce7bc116d2418f2',
    messagingSenderId: '897963909111',
    projectId: 'kayla-test-3ccfd',
    authDomain: 'kayla-test-3ccfd.firebaseapp.com',
    storageBucket: 'kayla-test-3ccfd.appspot.com',
    measurementId: 'G-8G0GX0X25F',
  );
}
